# name: php-and-mysql
services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - default
  php:
    image: krolnoeurnrpisb/usea-php-app:${PHP_APP_VERSION:-1.0.0}
    # build: ./Dockerfile
    container_name: php8.3
    restart: always
    depends_on:
      - mysql
    networks:
      - default
    environment:
      DB_HOST: mysql
      DB_DATABASE: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    volumes:
      - ./:/var/www/html
    ports:
      - "8090:80"
    
volumes:
  mysql_data:
networks:
  default:
    driver: bridge